### App requests.http

### Obtenir le token csrf
# @name getCsrf
GET http://localhost:3000/csrf/csrfToken

### Create a new user
POST http://localhost:3000/users
Content-Type: application/json
X-CSRF-Token: {{getCsrf.response.body.$.csrfToken}}

{
"username":"yayafsddd",
"email": "rrrooddoqfdoorrrr@exffdddd.com",
"password": "sfdooddddorfdfsdfds22"
}

### User login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
"email": "rrrooddoqfdoorrrr@exffdddd.com",
"password": "sfdooddddorfdfsdfds22"
}

### test protected route with new csrf token
POST http://localhost:3000/users/announceNewCsrfToken
X-CSRF-Token: {{getCsrf.response.body.$.csrfToken}}

### Verify user signup email confirmation
POST http://localhost:3000/auth/verify?token=<token>

### Retrieve all users
GET http://localhost:3000/users

### Get a user by profile
GET http://localhost:3000/auth/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjU4LCJ1c2VybmFtZSI6InlheWFmc2RkZCIsImlhdCI6MTc2MTc4NDA2MywiZXhwIjoxNzYxNzg0MTIzfQ.qTL9tsWxxA43GoKUOoh0Goz-U8sfmcYLR_r2QCNDNjo.eyJzdWIiOjU4LCJ1c2VybmFtZSI6InlheWFmc2RkZCIsImlhdCI6MTc2MTc4MjE4NywiZXhwIjoxNzYxNzgyMjQ3fQ.4SrxsMWlo4lrq6o3RoFlAE9TGwMC0X4uucLTGgkYfVo

### Find email availability
GET http://localhost:3000/users/email-availability?email=mmm@example.com


### Test mailtrap email sending
GET http://localhost:3000/auth/test-email




