### App requests.http

### Obtenir le token csrf
# @name getCsrf
GET http://localhost:3000/csrf/csrfToken

### Create a new user
POST http://localhost:3000/users
Content-Type: application/json
X-CSRF-Token: {{getCsrf.response.body.$.csrfToken}}

{
"username":"rrrrrrrrrrr",
"email": "rrrrrrrrrrr@exffd.com",
"password": "rrrrrrrrrrrfdfsdfds22"
}

### User login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
"email": "rrrrrrrrrrr@exffd.com",
"password": "rrrrrrrrrrrfdfsdfds22"
}

### Verify user signup email confirmation
POST http://localhost:3000/auth/verify?token=<token>


### Retrieve all users
GET http://localhost:3000/users

### Get a user by profile
GET http://localhost:3000/auth/profile
Authorization: Bearer <token>

### Find email availability
GET http://localhost:3000/users/email-availability?email=mmm@example.com


### Test mailtrap email sending
GET http://localhost:3000/auth/test-email




