### App requests.http

### Create a new user
POST http://localhost:3000/users
Content-Type: application/json

{
"username": "mmmgkjgkgh122",
"email": "mmm@example.com",
"password": "securePassword1112211"
}

### Retrieve all users
GET http://localhost:3000/users


